### ISSUE TITLE
Do you plan to add support for remote clients? 

### ISSUE THREAD

**Issue by gylli251** [Hellowlol/bw_plex#16] opened 2018-03-29 14:43 UTC
Do you plan to add support for remote clients?

**Comment by Hellowlol** [comment] 2018-03-29 16:18
I don’t think that is possible, not unless the ports to the clients are open on the firewall they are using. SyncLounge cheats but controlling the client from within there local network.

**Comment by gylli251** [comment] 2018-03-30 13:32
Might the be a solution in adding at as plex plugin or google chrome plugin ?

**Comment by Hellowlol** [comment] 2018-03-30 16:55
Plex plugin is not gonna happen as the plugin system is way to restricted. 

Chrome plugin is out of the question as my js is shit. It would also require web server inside bw_plex. I might revisit the webserver part if a api is added. Are you using plex cloud or running this on a vps? If so install bw_plex inside your local network.

**Comment by gylli251** [comment] 2018-03-30 17:09
Most of my users are not on my network. That's why I want remote as a feature. Would the solution be using a Webserver?

**Comment by Hellowlol** [comment] 2018-03-30 18:53
Not really, the problem is to reach the clients. You users would have to have a webserver then could receive a command and relay that to a client.

**Comment by Hellowlol** [comment] 2018-08-16 13:16
Closing this as we cant control remote clients atm.

**Closed by Hellowlol** 2018-08-16 13:16 UTC
